package uk.ac.gla.cvr.gluetools.core.reporting.contentNotes;

import uk.ac.gla.cvr.gluetools.core.document.ObjectBuilder;
import uk.ac.gla.cvr.gluetools.core.segments.IReferenceSegment;

/**
 * A sequence content note is a small object generated by the analysis pointing out something in the sequence content.
 */
public class SequenceContentNote implements IReferenceSegment {
	
	private int refStart;
	private int refEnd;
	
	public SequenceContentNote(int refStart, int refEnd) {
		super();
		this.refStart = refStart;
		this.refEnd = refEnd;
	}

	public void toDocument(ObjectBuilder sequenceDifferenceObj) {
		sequenceDifferenceObj.set("refStart", getRefStart());
		sequenceDifferenceObj.set("refEnd", getRefEnd());
	}
	
	@Override
	public Integer getRefStart() {
		return refStart;
	}

	@Override
	public Integer getRefEnd() {
		return refEnd;
	}

	@Override
	public void setRefStart(Integer refStart) {
		this.refStart = refStart;
	}

	@Override
	public void setRefEnd(Integer refEnd) {
		this.refEnd = refEnd;
	}

	public SequenceContentNote clone() {
		return new SequenceContentNote(getRefStart(), getRefEnd());
	}
	
}