FROM ubuntu:16.04
ARG glueVersion

RUN apt-get update 
# debconf-utils and python-software-properties manipulate package installer settings to allow non-interactive config
RUN apt-get install --no-install-recommends -y debconf-utils python-software-properties	    
	    
# Use set-selections to pre-populate mysql root password
RUN echo "mysql-server mysql-server/root_password password root123" | debconf-set-selections
RUN echo "mysql-server mysql-server/root_password_again password root123" | debconf-set-selections

# install mysql server
RUN apt-get install --no-install-recommends -y mysql-server

# workaround for this: https://askubuntu.com/questions/737903/mysql-5-7-no-directory-logging-in-with-home
RUN usermod -d /var/lib/mysql/ mysql


# Start MySQL and create user and DB.
RUN mkdir -p /opt/gluetools/bin
COPY docker/startMySQL.sh /opt/gluetools/bin
RUN chmod a+rwx /opt/gluetools/bin/startMySQL.sh
COPY docker/initMySQL.sh /opt/gluetools/bin
RUN chmod a+rwx /opt/gluetools/bin/initMySQL.sh
RUN /opt/gluetools/bin/initMySQL.sh 

EXPOSE 3306

ENTRYPOINT mysqld


