package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignedSegment.AlignedSegment;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _AlignmentMember was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AlignmentMember extends GlueDataObject {

    public static final String ALIGNED_SEGMENTS_PROPERTY = "alignedSegments";
    public static final String ALIGNMENT_PROPERTY = "alignment";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String ALIGNMENT_NAME_PK_COLUMN = "alignment_name";
    public static final String SEQUENCE_ID_PK_COLUMN = "sequence_id";
    public static final String SOURCE_NAME_PK_COLUMN = "source_name";

    public void addToAlignedSegments(AlignedSegment obj) {
        addToManyTarget(ALIGNED_SEGMENTS_PROPERTY, obj, true);
    }
    public void removeFromAlignedSegments(AlignedSegment obj) {
        removeToManyTarget(ALIGNED_SEGMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AlignedSegment> getAlignedSegments() {
        return (List<AlignedSegment>)readProperty(ALIGNED_SEGMENTS_PROPERTY);
    }


    public void setAlignment(Alignment alignment) {
        setToOneTarget(ALIGNMENT_PROPERTY, alignment, true);
    }

    public Alignment getAlignment() {
        return (Alignment)readProperty(ALIGNMENT_PROPERTY);
    }


    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
