/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignmentMember.AlignmentMember;

/**
 * Class _AlignedSegment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AlignedSegment extends GlueDataObject {

    public static final String MEMBER_END_PROPERTY = "memberEnd";
    public static final String MEMBER_START_PROPERTY = "memberStart";
    public static final String REF_END_PROPERTY = "refEnd";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String ALIGNMENT_MEMBER_PROPERTY = "alignmentMember";

    public static final String ALIGNMENT_NAME_PK_COLUMN = "alignment_name";
    public static final String MEMBER_END_PK_COLUMN = "member_end";
    public static final String MEMBER_START_PK_COLUMN = "member_start";
    public static final String REF_END_PK_COLUMN = "ref_end";
    public static final String REF_START_PK_COLUMN = "ref_start";
    public static final String SEQUENCE_ID_PK_COLUMN = "sequence_id";
    public static final String SOURCE_NAME_PK_COLUMN = "source_name";

    public void setMemberEnd(Integer memberEnd) {
        writeProperty(MEMBER_END_PROPERTY, memberEnd);
    }
    public Integer getMemberEnd() {
        return (Integer)readProperty(MEMBER_END_PROPERTY);
    }

    public void setMemberStart(Integer memberStart) {
        writeProperty(MEMBER_START_PROPERTY, memberStart);
    }
    public Integer getMemberStart() {
        return (Integer)readProperty(MEMBER_START_PROPERTY);
    }

    public void setRefEnd(Integer refEnd) {
        writeProperty(REF_END_PROPERTY, refEnd);
    }
    public Integer getRefEnd() {
        return (Integer)readProperty(REF_END_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setAlignmentMember(AlignmentMember alignmentMember) {
        setToOneTarget(ALIGNMENT_MEMBER_PROPERTY, alignmentMember, true);
    }

    public AlignmentMember getAlignmentMember() {
        return (AlignmentMember)readProperty(ALIGNMENT_MEMBER_PROPERTY);
    }


}
