package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignmentMember.AlignmentMember;

/**
 * Class _AlignedSegment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AlignedSegment extends GlueDataObject {

    public static final String LENGTH_PROPERTY = "length";
    public static final String MEMBER_START_PROPERTY = "memberStart";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String ALIGNMENT_MEMBER_PROPERTY = "alignmentMember";

    public static final String ALIGNMENT_PK_COLUMN = "ALIGNMENT";
    public static final String LENGTH_PK_COLUMN = "LENGTH";
    public static final String MEMBER_START_PK_COLUMN = "MEMBER_START";
    public static final String REF_START_PK_COLUMN = "REF_START";
    public static final String SEQUENCE_PK_COLUMN = "SEQUENCE";
    public static final String SOURCE_PK_COLUMN = "SOURCE";

    public void setLength(Integer length) {
        writeProperty(LENGTH_PROPERTY, length);
    }
    public Integer getLength() {
        return (Integer)readProperty(LENGTH_PROPERTY);
    }

    public void setMemberStart(Integer memberStart) {
        writeProperty(MEMBER_START_PROPERTY, memberStart);
    }
    public Integer getMemberStart() {
        return (Integer)readProperty(MEMBER_START_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setAlignmentMember(AlignmentMember alignmentMember) {
        setToOneTarget(ALIGNMENT_MEMBER_PROPERTY, alignmentMember, true);
    }

    public AlignmentMember getAlignmentMember() {
        return (AlignmentMember)readProperty(ALIGNMENT_MEMBER_PROPERTY);
    }


}
