/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignedSegment.AlignedSegment;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.memberFLocNote.MemberFLocNote;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _AlignmentMember was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AlignmentMember extends GlueDataObject {

    public static final String REFERENCE_MEMBER_PROPERTY = "referenceMember";
    public static final String ALIGNED_SEGMENTS_PROPERTY = "alignedSegments";
    public static final String ALIGNMENT_PROPERTY = "alignment";
    public static final String F_LOC_NOTES_PROPERTY = "fLocNotes";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String ALIGNMENT_NAME_PK_COLUMN = "alignment_name";
    public static final String SEQUENCE_ID_PK_COLUMN = "sequence_id";
    public static final String SOURCE_NAME_PK_COLUMN = "source_name";

    public void setReferenceMember(Boolean referenceMember) {
        writeProperty(REFERENCE_MEMBER_PROPERTY, referenceMember);
    }
    public Boolean getReferenceMember() {
        return (Boolean)readProperty(REFERENCE_MEMBER_PROPERTY);
    }

    public void addToAlignedSegments(AlignedSegment obj) {
        addToManyTarget(ALIGNED_SEGMENTS_PROPERTY, obj, true);
    }
    public void removeFromAlignedSegments(AlignedSegment obj) {
        removeToManyTarget(ALIGNED_SEGMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AlignedSegment> getAlignedSegments() {
        return (List<AlignedSegment>)readProperty(ALIGNED_SEGMENTS_PROPERTY);
    }


    public void setAlignment(Alignment alignment) {
        setToOneTarget(ALIGNMENT_PROPERTY, alignment, true);
    }

    public Alignment getAlignment() {
        return (Alignment)readProperty(ALIGNMENT_PROPERTY);
    }


    public void addToFLocNotes(MemberFLocNote obj) {
        addToManyTarget(F_LOC_NOTES_PROPERTY, obj, true);
    }
    public void removeFromFLocNotes(MemberFLocNote obj) {
        removeToManyTarget(F_LOC_NOTES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MemberFLocNote> getFLocNotes() {
        return (List<MemberFLocNote>)readProperty(F_LOC_NOTES_PROPERTY);
    }


    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
