package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignmentMember.AlignmentMember;
import uk.ac.gla.cvr.gluetools.core.datamodel.refSequence.ReferenceSequence;

/**
 * Class _Alignment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Alignment extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String CHILDREN_PROPERTY = "children";
    public static final String MEMBERS_PROPERTY = "members";
    public static final String PARENT_PROPERTY = "parent";
    public static final String REF_SEQUENCE_PROPERTY = "refSequence";

    public static final String NAME_PK_COLUMN = "NAME";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToChildren(Alignment obj) {
        addToManyTarget(CHILDREN_PROPERTY, obj, true);
    }
    public void removeFromChildren(Alignment obj) {
        removeToManyTarget(CHILDREN_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Alignment> getChildren() {
        return (List<Alignment>)readProperty(CHILDREN_PROPERTY);
    }


    public void addToMembers(AlignmentMember obj) {
        addToManyTarget(MEMBERS_PROPERTY, obj, true);
    }
    public void removeFromMembers(AlignmentMember obj) {
        removeToManyTarget(MEMBERS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AlignmentMember> getMembers() {
        return (List<AlignmentMember>)readProperty(MEMBERS_PROPERTY);
    }


    public void setParent(Alignment parent) {
        setToOneTarget(PARENT_PROPERTY, parent, true);
    }

    public Alignment getParent() {
        return (Alignment)readProperty(PARENT_PROPERTY);
    }


    public void setRefSequence(ReferenceSequence refSequence) {
        setToOneTarget(REF_SEQUENCE_PROPERTY, refSequence, true);
    }

    public ReferenceSequence getRefSequence() {
        return (ReferenceSequence)readProperty(REF_SEQUENCE_PROPERTY);
    }


}
