package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.project.Project;

/**
 * Class _CustomTable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CustomTable extends GlueDataObject {

    public static final String ID_FIELD_LENGTH_PROPERTY = "idFieldLength";
    public static final String NAME_PROPERTY = "name";
    public static final String PROJECT_PROPERTY = "project";

    public static final String NAME_PK_COLUMN = "name";
    public static final String PROJECT_NAME_PK_COLUMN = "project_name";

    public void setIdFieldLength(Integer idFieldLength) {
        writeProperty(ID_FIELD_LENGTH_PROPERTY, idFieldLength);
    }
    public Integer getIdFieldLength() {
        return (Integer)readProperty(ID_FIELD_LENGTH_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setProject(Project project) {
        setToOneTarget(PROJECT_PROPERTY, project, true);
    }

    public Project getProject() {
        return (Project)readProperty(PROJECT_PROPERTY);
    }


}
