/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.feature.Feature;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureSegment.FeatureSegment;
import uk.ac.gla.cvr.gluetools.core.datamodel.memberFLocNote.MemberFLocNote;
import uk.ac.gla.cvr.gluetools.core.datamodel.refSequence.ReferenceSequence;
import uk.ac.gla.cvr.gluetools.core.datamodel.variation.Variation;

/**
 * Class _FeatureLocation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeatureLocation extends GlueDataObject {

    public static final String FEATURE_PROPERTY = "feature";
    public static final String MEMBER_FLOC_NOTES_PROPERTY = "memberFLocNotes";
    public static final String REFERENCE_SEQUENCE_PROPERTY = "referenceSequence";
    public static final String SEGMENTS_PROPERTY = "segments";
    public static final String VARIATIONS_PROPERTY = "variations";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";

    public void setFeature(Feature feature) {
        setToOneTarget(FEATURE_PROPERTY, feature, true);
    }

    public Feature getFeature() {
        return (Feature)readProperty(FEATURE_PROPERTY);
    }


    public void addToMemberFLocNotes(MemberFLocNote obj) {
        addToManyTarget(MEMBER_FLOC_NOTES_PROPERTY, obj, true);
    }
    public void removeFromMemberFLocNotes(MemberFLocNote obj) {
        removeToManyTarget(MEMBER_FLOC_NOTES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MemberFLocNote> getMemberFLocNotes() {
        return (List<MemberFLocNote>)readProperty(MEMBER_FLOC_NOTES_PROPERTY);
    }


    public void setReferenceSequence(ReferenceSequence referenceSequence) {
        setToOneTarget(REFERENCE_SEQUENCE_PROPERTY, referenceSequence, true);
    }

    public ReferenceSequence getReferenceSequence() {
        return (ReferenceSequence)readProperty(REFERENCE_SEQUENCE_PROPERTY);
    }


    public void addToSegments(FeatureSegment obj) {
        addToManyTarget(SEGMENTS_PROPERTY, obj, true);
    }
    public void removeFromSegments(FeatureSegment obj) {
        removeToManyTarget(SEGMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureSegment> getSegments() {
        return (List<FeatureSegment>)readProperty(SEGMENTS_PROPERTY);
    }


    public void addToVariations(Variation obj) {
        addToManyTarget(VARIATIONS_PROPERTY, obj, true);
    }
    public void removeFromVariations(Variation obj) {
        removeToManyTarget(VARIATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Variation> getVariations() {
        return (List<Variation>)readProperty(VARIATIONS_PROPERTY);
    }


}
