package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.feature.Feature;

/**
 * Class _FeatureMetatag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeatureMetatag extends GlueDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String VALUE_PROPERTY = "value";
    public static final String FEATURE_PROPERTY = "feature";

    public static final String FEATURE_NAME_PK_COLUMN = "FEATURE_NAME";
    public static final String NAME_PK_COLUMN = "NAME";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setValue(String value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public String getValue() {
        return (String)readProperty(VALUE_PROPERTY);
    }

    public void setFeature(Feature feature) {
        setToOneTarget(FEATURE_PROPERTY, feature, true);
    }

    public Feature getFeature() {
        return (Feature)readProperty(FEATURE_PROPERTY);
    }


}
