/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;

/**
 * Class _FeatureSegment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeatureSegment extends GlueDataObject {

    public static final String PRE_TRANSLATION_MODIFIER_NAME_PROPERTY = "preTranslationModifierName";
    public static final String REF_END_PROPERTY = "refEnd";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String FEATURE_LOCATION_PROPERTY = "featureLocation";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String REF_END_PK_COLUMN = "ref_end";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";
    public static final String REF_START_PK_COLUMN = "ref_start";

    public void setPreTranslationModifierName(String preTranslationModifierName) {
        writeProperty(PRE_TRANSLATION_MODIFIER_NAME_PROPERTY, preTranslationModifierName);
    }
    public String getPreTranslationModifierName() {
        return (String)readProperty(PRE_TRANSLATION_MODIFIER_NAME_PROPERTY);
    }

    public void setRefEnd(Integer refEnd) {
        writeProperty(REF_END_PROPERTY, refEnd);
    }
    public Integer getRefEnd() {
        return (Integer)readProperty(REF_END_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setFeatureLocation(FeatureLocation featureLocation) {
        setToOneTarget(FEATURE_LOCATION_PROPERTY, featureLocation, true);
    }

    public FeatureLocation getFeatureLocation() {
        return (FeatureLocation)readProperty(FEATURE_LOCATION_PROPERTY);
    }


}
