package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;

/**
 * Class _FeatureSegment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeatureSegment extends GlueDataObject {

    public static final String REF_END_PROPERTY = "refEnd";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String FEATURE_LOCATION_PROPERTY = "featureLocation";

    public static final String FEATURE_PK_COLUMN = "FEATURE";
    public static final String REF_END_PK_COLUMN = "REF_END";
    public static final String REF_SEQUENCE_PK_COLUMN = "REF_SEQUENCE";
    public static final String REF_START_PK_COLUMN = "REF_START";

    public void setRefEnd(Integer refEnd) {
        writeProperty(REF_END_PROPERTY, refEnd);
    }
    public Integer getRefEnd() {
        return (Integer)readProperty(REF_END_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setFeatureLocation(FeatureLocation featureLocation) {
        setToOneTarget(FEATURE_LOCATION_PROPERTY, featureLocation, true);
    }

    public FeatureLocation getFeatureLocation() {
        return (FeatureLocation)readProperty(FEATURE_LOCATION_PROPERTY);
    }


}
