package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;

/**
 * Class _Feature was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Feature extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String TRANSCRIPTION_TYPE_PROPERTY = "transcriptionType";
    public static final String FEATURE_LOCATIONS_PROPERTY = "featureLocations";

    public static final String NAME_PK_COLUMN = "NAME";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setTranscriptionType(String transcriptionType) {
        writeProperty(TRANSCRIPTION_TYPE_PROPERTY, transcriptionType);
    }
    public String getTranscriptionType() {
        return (String)readProperty(TRANSCRIPTION_TYPE_PROPERTY);
    }

    public void addToFeatureLocations(FeatureLocation obj) {
        addToManyTarget(FEATURE_LOCATIONS_PROPERTY, obj, true);
    }
    public void removeFromFeatureLocations(FeatureLocation obj) {
        removeToManyTarget(FEATURE_LOCATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureLocation> getFeatureLocations() {
        return (List<FeatureLocation>)readProperty(FEATURE_LOCATIONS_PROPERTY);
    }


}
