package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.project.Project;

/**
 * Class _Field was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Field extends GlueDataObject {

    public static final String MAX_LENGTH_PROPERTY = "maxLength";
    public static final String NAME_PROPERTY = "name";
    public static final String TABLE_PROPERTY = "table";
    public static final String TYPE_PROPERTY = "type";
    public static final String PROJECT_PROPERTY = "project";

    public static final String NAME_PK_COLUMN = "name";
    public static final String PROJECT_NAME_PK_COLUMN = "project_name";
    public static final String TABLE_NAME_PK_COLUMN = "table_name";

    public void setMaxLength(Integer maxLength) {
        writeProperty(MAX_LENGTH_PROPERTY, maxLength);
    }
    public Integer getMaxLength() {
        return (Integer)readProperty(MAX_LENGTH_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setTable(String table) {
        writeProperty(TABLE_PROPERTY, table);
    }
    public String getTable() {
        return (String)readProperty(TABLE_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

    public void setProject(Project project) {
        setToOneTarget(PROJECT_PROPERTY, project, true);
    }

    public Project getProject() {
        return (Project)readProperty(PROJECT_PROPERTY);
    }


}
