package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;
import uk.ac.gla.cvr.gluetools.core.sequenceGroup.SequenceGroup;

/**
 * Class _GroupMember was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _GroupMember extends GlueDataObject {

    public static final String GROUP_PROPERTY = "group";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String GROUP_NAME_PK_COLUMN = "group_name";
    public static final String SEQUENCE_ID_PK_COLUMN = "sequence_id";
    public static final String SOURCE_NAME_PK_COLUMN = "source_name";

    public void setGroup(SequenceGroup group) {
        setToOneTarget(GROUP_PROPERTY, group, true);
    }

    public SequenceGroup getGroup() {
        return (SequenceGroup)readProperty(GROUP_PROPERTY);
    }


    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
