/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.project.Project;

/**
 * Class _LinkField was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LinkField extends GlueDataObject {

    public static final String DEST_TABLE_NAME_PROPERTY = "destTableName";
    public static final String MULTIPLICITY_PROPERTY = "multiplicity";
    public static final String NAME_PROPERTY = "name";
    public static final String TABLE_PROPERTY = "table";
    public static final String PROJECT_PROPERTY = "project";

    public static final String NAME_PK_COLUMN = "name";
    public static final String PROJECT_NAME_PK_COLUMN = "project_name";
    public static final String TABLE_NAME_PK_COLUMN = "table_name";

    public void setDestTableName(String destTableName) {
        writeProperty(DEST_TABLE_NAME_PROPERTY, destTableName);
    }
    public String getDestTableName() {
        return (String)readProperty(DEST_TABLE_NAME_PROPERTY);
    }

    public void setMultiplicity(String multiplicity) {
        writeProperty(MULTIPLICITY_PROPERTY, multiplicity);
    }
    public String getMultiplicity() {
        return (String)readProperty(MULTIPLICITY_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setTable(String table) {
        writeProperty(TABLE_PROPERTY, table);
    }
    public String getTable() {
        return (String)readProperty(TABLE_PROPERTY);
    }

    public void setProject(Project project) {
        setToOneTarget(PROJECT_PROPERTY, project, true);
    }

    public Project getProject() {
        return (Project)readProperty(PROJECT_PROPERTY);
    }


}
