package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.project.Project;

/**
 * Class _Link was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Link extends GlueDataObject {

    public static final String DEST_LINK_NAME_PROPERTY = "destLinkName";
    public static final String DEST_TABLE_NAME_PROPERTY = "destTableName";
    public static final String MULTIPLICITY_PROPERTY = "multiplicity";
    public static final String SRC_LINK_NAME_PROPERTY = "srcLinkName";
    public static final String SRC_TABLE_NAME_PROPERTY = "srcTableName";
    public static final String PROJECT_PROPERTY = "project";

    public static final String PROJECT_NAME_PK_COLUMN = "project_name";
    public static final String SRC_LINK_NAME_PK_COLUMN = "src_link_name";
    public static final String SRC_TABLE_NAME_PK_COLUMN = "src_table_name";

    public void setDestLinkName(String destLinkName) {
        writeProperty(DEST_LINK_NAME_PROPERTY, destLinkName);
    }
    public String getDestLinkName() {
        return (String)readProperty(DEST_LINK_NAME_PROPERTY);
    }

    public void setDestTableName(String destTableName) {
        writeProperty(DEST_TABLE_NAME_PROPERTY, destTableName);
    }
    public String getDestTableName() {
        return (String)readProperty(DEST_TABLE_NAME_PROPERTY);
    }

    public void setMultiplicity(String multiplicity) {
        writeProperty(MULTIPLICITY_PROPERTY, multiplicity);
    }
    public String getMultiplicity() {
        return (String)readProperty(MULTIPLICITY_PROPERTY);
    }

    public void setSrcLinkName(String srcLinkName) {
        writeProperty(SRC_LINK_NAME_PROPERTY, srcLinkName);
    }
    public String getSrcLinkName() {
        return (String)readProperty(SRC_LINK_NAME_PROPERTY);
    }

    public void setSrcTableName(String srcTableName) {
        writeProperty(SRC_TABLE_NAME_PROPERTY, srcTableName);
    }
    public String getSrcTableName() {
        return (String)readProperty(SRC_TABLE_NAME_PROPERTY);
    }

    public void setProject(Project project) {
        setToOneTarget(PROJECT_PROPERTY, project, true);
    }

    public Project getProject() {
        return (Project)readProperty(PROJECT_PROPERTY);
    }


}
