package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.moduleResource.ModuleResource;

/**
 * Class _Module was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Module extends GlueDataObject {

    public static final String CONFIG_PROPERTY = "config";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String RESOURCES_PROPERTY = "resources";

    public static final String NAME_PK_COLUMN = "name";

    public void setConfig(byte[] config) {
        writeProperty(CONFIG_PROPERTY, config);
    }
    public byte[] getConfig() {
        return (byte[])readProperty(CONFIG_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToResources(ModuleResource obj) {
        addToManyTarget(RESOURCES_PROPERTY, obj, true);
    }
    public void removeFromResources(ModuleResource obj) {
        removeToManyTarget(RESOURCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ModuleResource> getResources() {
        return (List<ModuleResource>)readProperty(RESOURCES_PROPERTY);
    }


}
