package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.module.Module;

/**
 * Class _ModuleResource was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ModuleResource extends GlueDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String NAME_PROPERTY = "name";
    public static final String MODULE_PROPERTY = "module";

    public static final String MODULE_NAME_PK_COLUMN = "module_name";
    public static final String NAME_PK_COLUMN = "name";

    public void setContent(byte[] content) {
        writeProperty(CONTENT_PROPERTY, content);
    }
    public byte[] getContent() {
        return (byte[])readProperty(CONTENT_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setModule(Module module) {
        setToOneTarget(MODULE_PROPERTY, module, true);
    }

    public Module getModule() {
        return (Module)readProperty(MODULE_PROPERTY);
    }


}
