package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.variation.Variation;

/**
 * Class _PatternLocation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PatternLocation extends GlueDataObject {

    public static final String PATTERN_PROPERTY = "pattern";
    public static final String REF_END_PROPERTY = "refEnd";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String VARIATION_PROPERTY = "variation";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String REF_END_PK_COLUMN = "ref_end";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";
    public static final String REF_START_PK_COLUMN = "ref_start";
    public static final String VARIATION_NAME_PK_COLUMN = "variation_name";

    public void setPattern(String pattern) {
        writeProperty(PATTERN_PROPERTY, pattern);
    }
    public String getPattern() {
        return (String)readProperty(PATTERN_PROPERTY);
    }

    public void setRefEnd(Integer refEnd) {
        writeProperty(REF_END_PROPERTY, refEnd);
    }
    public Integer getRefEnd() {
        return (Integer)readProperty(REF_END_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setVariation(Variation variation) {
        setToOneTarget(VARIATION_PROPERTY, variation, true);
    }

    public Variation getVariation() {
        return (Variation)readProperty(VARIATION_PROPERTY);
    }


}
