package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;
import uk.ac.gla.cvr.gluetools.core.datamodel.variation.Variation;

/**
 * Class _PositionVariation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PositionVariation extends GlueDataObject {

    public static final String POSITION_PROPERTY = "position";
    public static final String TRANSLATION_TYPE_PROPERTY = "translationType";
    public static final String FEATURE_LOCATION_PROPERTY = "featureLocation";
    public static final String VARIATION_PROPERTY = "variation";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String POSITION_PK_COLUMN = "position";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";
    public static final String TRANSLATION_TYPE_PK_COLUMN = "translation_type";
    public static final String VARIATION_NAME_PK_COLUMN = "variation_name";

    public void setPosition(Integer position) {
        writeProperty(POSITION_PROPERTY, position);
    }
    public Integer getPosition() {
        return (Integer)readProperty(POSITION_PROPERTY);
    }

    public void setTranslationType(String translationType) {
        writeProperty(TRANSLATION_TYPE_PROPERTY, translationType);
    }
    public String getTranslationType() {
        return (String)readProperty(TRANSLATION_TYPE_PROPERTY);
    }

    public void setFeatureLocation(FeatureLocation featureLocation) {
        setToOneTarget(FEATURE_LOCATION_PROPERTY, featureLocation, true);
    }

    public FeatureLocation getFeatureLocation() {
        return (FeatureLocation)readProperty(FEATURE_LOCATION_PROPERTY);
    }


    public void setVariation(Variation variation) {
        setToOneTarget(VARIATION_PROPERTY, variation, true);
    }

    public Variation getVariation() {
        return (Variation)readProperty(VARIATION_PROPERTY);
    }


}
