package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.field.Field;
import uk.ac.gla.cvr.gluetools.core.datamodel.module.Module;
import uk.ac.gla.cvr.gluetools.core.datamodel.source.Source;

/**
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Project extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String FIELDS_PROPERTY = "fields";
    public static final String MODULES_PROPERTY = "modules";
    public static final String SOURCES_PROPERTY = "sources";

    public static final String NAME_PK_COLUMN = "NAME";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToFields(Field obj) {
        addToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    public void removeFromFields(Field obj) {
        removeToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Field> getFields() {
        return (List<Field>)readProperty(FIELDS_PROPERTY);
    }


    public void addToModules(Module obj) {
        addToManyTarget(MODULES_PROPERTY, obj, true);
    }
    public void removeFromModules(Module obj) {
        removeToManyTarget(MODULES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Module> getModules() {
        return (List<Module>)readProperty(MODULES_PROPERTY);
    }


    public void addToSources(Source obj) {
        addToManyTarget(SOURCES_PROPERTY, obj, true);
    }
    public void removeFromSources(Source obj) {
        removeToManyTarget(SOURCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Source> getSources() {
        return (List<Source>)readProperty(SOURCES_PROPERTY);
    }


}
