/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.customtable.CustomTable;
import uk.ac.gla.cvr.gluetools.core.datamodel.field.Field;
import uk.ac.gla.cvr.gluetools.core.datamodel.link.Link;

/**
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Project extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String CUSTOM_TABLES_PROPERTY = "customTables";
    public static final String FIELDS_PROPERTY = "fields";
    public static final String LINKS_PROPERTY = "links";

    public static final String NAME_PK_COLUMN = "name";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToCustomTables(CustomTable obj) {
        addToManyTarget(CUSTOM_TABLES_PROPERTY, obj, true);
    }
    public void removeFromCustomTables(CustomTable obj) {
        removeToManyTarget(CUSTOM_TABLES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CustomTable> getCustomTables() {
        return (List<CustomTable>)readProperty(CUSTOM_TABLES_PROPERTY);
    }


    public void addToFields(Field obj) {
        addToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    public void removeFromFields(Field obj) {
        removeToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Field> getFields() {
        return (List<Field>)readProperty(FIELDS_PROPERTY);
    }


    public void addToLinks(Link obj) {
        addToManyTarget(LINKS_PROPERTY, obj, true);
    }
    public void removeFromLinks(Link obj) {
        removeToManyTarget(LINKS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Link> getLinks() {
        return (List<Link>)readProperty(LINKS_PROPERTY);
    }


}
