package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.field.Field;

/**
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Project extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String FIELDS_PROPERTY = "fields";

    public static final String NAME_PK_COLUMN = "name";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToFields(Field obj) {
        addToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    public void removeFromFields(Field obj) {
        removeToManyTarget(FIELDS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Field> getFields() {
        return (List<Field>)readProperty(FIELDS_PROPERTY);
    }


}
