package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.feature.Feature;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _ReferenceSequence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReferenceSequence extends GlueDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String ALIGNMENTS_PROPERTY = "alignments";
    public static final String FEATURES_PROPERTY = "features";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String NAME_PK_COLUMN = "NAME";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToAlignments(Alignment obj) {
        addToManyTarget(ALIGNMENTS_PROPERTY, obj, true);
    }
    public void removeFromAlignments(Alignment obj) {
        removeToManyTarget(ALIGNMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Alignment> getAlignments() {
        return (List<Alignment>)readProperty(ALIGNMENTS_PROPERTY);
    }


    public void addToFeatures(Feature obj) {
        addToManyTarget(FEATURES_PROPERTY, obj, true);
    }
    public void removeFromFeatures(Feature obj) {
        removeToManyTarget(FEATURES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Feature> getFeatures() {
        return (List<Feature>)readProperty(FEATURES_PROPERTY);
    }


    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
