package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _ReferenceSequence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReferenceSequence extends GlueDataObject {

    public static final String CREATION_TIME_PROPERTY = "creationTime";
    public static final String NAME_PROPERTY = "name";
    public static final String ALIGNMENTS_PROPERTY = "alignments";
    public static final String FEATURE_LOCATIONS_PROPERTY = "featureLocations";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String NAME_PK_COLUMN = "name";

    public void setCreationTime(long creationTime) {
        writeProperty(CREATION_TIME_PROPERTY, creationTime);
    }
    public long getCreationTime() {
        Object value = readProperty(CREATION_TIME_PROPERTY);
        return (value != null) ? (Long) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToAlignments(Alignment obj) {
        addToManyTarget(ALIGNMENTS_PROPERTY, obj, true);
    }
    public void removeFromAlignments(Alignment obj) {
        removeToManyTarget(ALIGNMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Alignment> getAlignments() {
        return (List<Alignment>)readProperty(ALIGNMENTS_PROPERTY);
    }


    public void addToFeatureLocations(FeatureLocation obj) {
        addToManyTarget(FEATURE_LOCATIONS_PROPERTY, obj, true);
    }
    public void removeFromFeatureLocations(FeatureLocation obj) {
        removeToManyTarget(FEATURE_LOCATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureLocation> getFeatureLocations() {
        return (List<FeatureLocation>)readProperty(FEATURE_LOCATIONS_PROPERTY);
    }


    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
