/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _ReferenceSequence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReferenceSequence extends GlueDataObject {

    public static final String CREATION_TIME_PROPERTY = "creationTime";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String NAME_PROPERTY = "name";
    public static final String ALIGNMENTS_WHERE_REF_SEQUENCE_PROPERTY = "alignmentsWhereRefSequence";
    public static final String FEATURE_LOCATIONS_PROPERTY = "featureLocations";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String NAME_PK_COLUMN = "name";

    public void setCreationTime(long creationTime) {
        writeProperty(CREATION_TIME_PROPERTY, creationTime);
    }
    public long getCreationTime() {
        Object value = readProperty(CREATION_TIME_PROPERTY);
        return (value != null) ? (Long) value : 0;
    }

    public void setDisplayName(String displayName) {
        writeProperty(DISPLAY_NAME_PROPERTY, displayName);
    }
    public String getDisplayName() {
        return (String)readProperty(DISPLAY_NAME_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToAlignmentsWhereRefSequence(Alignment obj) {
        addToManyTarget(ALIGNMENTS_WHERE_REF_SEQUENCE_PROPERTY, obj, true);
    }
    public void removeFromAlignmentsWhereRefSequence(Alignment obj) {
        removeToManyTarget(ALIGNMENTS_WHERE_REF_SEQUENCE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Alignment> getAlignmentsWhereRefSequence() {
        return (List<Alignment>)readProperty(ALIGNMENTS_WHERE_REF_SEQUENCE_PROPERTY);
    }


    public void addToFeatureLocations(FeatureLocation obj) {
        addToManyTarget(FEATURE_LOCATIONS_PROPERTY, obj, true);
    }
    public void removeFromFeatureLocations(FeatureLocation obj) {
        removeToManyTarget(FEATURE_LOCATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FeatureLocation> getFeatureLocations() {
        return (List<FeatureLocation>)readProperty(FEATURE_LOCATIONS_PROPERTY);
    }


    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
