package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;

/**
 * Class _SchemaVersion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SchemaVersion extends GlueDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String SCHEMA_VERSION_PROPERTY = "schemaVersion";

    public static final String ID_PK_COLUMN = "ID";

    public void setId(int id) {
        writeProperty(ID_PROPERTY, id);
    }
    public int getId() {
        Object value = readProperty(ID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setSchemaVersion(String schemaVersion) {
        writeProperty(SCHEMA_VERSION_PROPERTY, schemaVersion);
    }
    public String getSchemaVersion() {
        return (String)readProperty(SCHEMA_VERSION_PROPERTY);
    }

}
