/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;

/**
 * Class _SchemaVersion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SchemaVersion extends GlueDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String SCHEMA_VERSION_PROPERTY = "schemaVersion";

    public static final String ID_PK_COLUMN = "id";

    public void setId(int id) {
        writeProperty(ID_PROPERTY, id);
    }
    public int getId() {
        Object value = readProperty(ID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setSchemaVersion(String schemaVersion) {
        writeProperty(SCHEMA_VERSION_PROPERTY, schemaVersion);
    }
    public String getSchemaVersion() {
        return (String)readProperty(SCHEMA_VERSION_PROPERTY);
    }

}
