package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.groupMember.GroupMember;

/**
 * Class _SequenceGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SequenceGroup extends GlueDataObject {

    public static final String LAST_UPDATE_TIME_PROPERTY = "lastUpdateTime";
    public static final String NAME_PROPERTY = "name";
    public static final String MEMBERS_PROPERTY = "members";

    public static final String NAME_PK_COLUMN = "name";

    public void setLastUpdateTime(long lastUpdateTime) {
        writeProperty(LAST_UPDATE_TIME_PROPERTY, lastUpdateTime);
    }
    public long getLastUpdateTime() {
        Object value = readProperty(LAST_UPDATE_TIME_PROPERTY);
        return (value != null) ? (Long) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToMembers(GroupMember obj) {
        addToManyTarget(MEMBERS_PROPERTY, obj, true);
    }
    public void removeFromMembers(GroupMember obj) {
        removeToManyTarget(MEMBERS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<GroupMember> getMembers() {
        return (List<GroupMember>)readProperty(MEMBERS_PROPERTY);
    }


}
