package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _SeqOrigData was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SeqOrigData extends GlueDataObject {

    public static final String PACKED_DATA_PROPERTY = "packedData";
    public static final String SEQUENCE_PROPERTY = "sequence";

    public static final String SEQUENCE_ID_PK_COLUMN = "SEQUENCE_ID";
    public static final String SOURCE_PK_COLUMN = "SOURCE";

    public void setPackedData(byte[] packedData) {
        writeProperty(PACKED_DATA_PROPERTY, packedData);
    }
    public byte[] getPackedData() {
        return (byte[])readProperty(PACKED_DATA_PROPERTY);
    }

    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


}
