package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.Project;
import uk.ac.gla.cvr.gluetools.core.datamodel.Sourcer;

/**
 * Class _Sequence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sequence extends GlueDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String SOURCER_ID_PROPERTY = "sourcerId";
    public static final String PROJECT_PROPERTY = "project";
    public static final String SOURCER_PROPERTY = "sourcer";

    public static final String ID_PK_COLUMN = "ID";

    public void setData(byte[] data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public byte[] getData() {
        return (byte[])readProperty(DATA_PROPERTY);
    }

    public void setSourcerId(String sourcerId) {
        writeProperty(SOURCER_ID_PROPERTY, sourcerId);
    }
    public String getSourcerId() {
        return (String)readProperty(SOURCER_ID_PROPERTY);
    }

    public void setProject(Project project) {
        setToOneTarget(PROJECT_PROPERTY, project, true);
    }

    public Project getProject() {
        return (Project)readProperty(PROJECT_PROPERTY);
    }


    public void setSourcer(Sourcer sourcer) {
        setToOneTarget(SOURCER_PROPERTY, sourcer, true);
    }

    public Sourcer getSourcer() {
        return (Sourcer)readProperty(SOURCER_PROPERTY);
    }


}
