package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;

/**
 * Class _Source was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Source extends GlueDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String SEQUENCES_PROPERTY = "sequences";

    public static final String NAME_PK_COLUMN = "NAME";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToSequences(Sequence obj) {
        addToManyTarget(SEQUENCES_PROPERTY, obj, true);
    }
    public void removeFromSequences(Sequence obj) {
        removeToManyTarget(SEQUENCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sequence> getSequences() {
        return (List<Sequence>)readProperty(SEQUENCES_PROPERTY);
    }


}
