package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.Project;
import uk.ac.gla.cvr.gluetools.core.datamodel.Sequence;

/**
 * Class _Sourcer was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sourcer extends GlueDataObject {

    public static final String CONFIG_PROPERTY = "config";
    public static final String PROJECT_PROPERTY = "project";
    public static final String SEQUENCES_PROPERTY = "sequences";

    public static final String NAME_PK_COLUMN = "NAME";
    public static final String PROJECT_PK_COLUMN = "PROJECT";

    public void setConfig(byte[] config) {
        writeProperty(CONFIG_PROPERTY, config);
    }
    public byte[] getConfig() {
        return (byte[])readProperty(CONFIG_PROPERTY);
    }

    public void setProject(Project project) {
        setToOneTarget(PROJECT_PROPERTY, project, true);
    }

    public Project getProject() {
        return (Project)readProperty(PROJECT_PROPERTY);
    }


    public void addToSequences(Sequence obj) {
        addToManyTarget(SEQUENCES_PROPERTY, obj, true);
    }
    public void removeFromSequences(Sequence obj) {
        removeToManyTarget(SEQUENCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Sequence> getSequences() {
        return (List<Sequence>)readProperty(SEQUENCES_PROPERTY);
    }


}
