package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.target.Target;

/**
 * Class _TargetSet was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TargetSet extends GlueDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String TARGETS_PROPERTY = "targets";

    public static final String NAME_PK_COLUMN = "NAME";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToTargets(Target obj) {
        addToManyTarget(TARGETS_PROPERTY, obj, true);
    }
    public void removeFromTargets(Target obj) {
        removeToManyTarget(TARGETS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Target> getTargets() {
        return (List<Target>)readProperty(TARGETS_PROPERTY);
    }


}
