package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.sequence.Sequence;
import uk.ac.gla.cvr.gluetools.core.targetSet.TargetSet;

/**
 * Class _Target was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Target extends GlueDataObject {

    public static final String SEQUENCE_PROPERTY = "sequence";
    public static final String TARGET_SET_PROPERTY = "targetSet";

    public static final String SEQUENCE_ID_PK_COLUMN = "SEQUENCE_ID";
    public static final String SOURCE_PK_COLUMN = "SOURCE";
    public static final String TARGET_SET_PK_COLUMN = "TARGET_SET";

    public void setSequence(Sequence sequence) {
        setToOneTarget(SEQUENCE_PROPERTY, sequence, true);
    }

    public Sequence getSequence() {
        return (Sequence)readProperty(SEQUENCE_PROPERTY);
    }


    public void setTargetSet(TargetSet targetSet) {
        setToOneTarget(TARGET_SET_PROPERTY, targetSet, true);
    }

    public TargetSet getTargetSet() {
        return (TargetSet)readProperty(TARGET_SET_PROPERTY);
    }


}
