/**
 *    GLUE: A flexible system for virus sequence data
 *    Copyright (C) 2018 The University of Glasgow
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as published
 *    by the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.

 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *    Contact details:
 *    MRC-University of Glasgow Centre for Virus Research
 *    Sir Michael Stoker Building, Garscube Campus, 464 Bearsden Road, 
 *    Glasgow G61 1QH, United Kingdom
 *    
 *    Josh Singer: josh.singer@glasgow.ac.uk
 *    Rob Gifford: robert.gifford@glasgow.ac.uk
*/
package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;
import uk.ac.gla.cvr.gluetools.core.datamodel.varAlmtNote.VarAlmtNote;
import uk.ac.gla.cvr.gluetools.core.datamodel.variationMetatag.VariationMetatag;

/**
 * Class _Variation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Variation extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String NAME_PROPERTY = "name";
    public static final String REF_END_PROPERTY = "refEnd";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String TYPE_PROPERTY = "type";
    public static final String FEATURE_LOC_PROPERTY = "featureLoc";
    public static final String METATAGS_PROPERTY = "metatags";
    public static final String VAR_ALMT_NOTES_PROPERTY = "varAlmtNotes";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String NAME_PK_COLUMN = "name";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setDisplayName(String displayName) {
        writeProperty(DISPLAY_NAME_PROPERTY, displayName);
    }
    public String getDisplayName() {
        return (String)readProperty(DISPLAY_NAME_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setRefEnd(Integer refEnd) {
        writeProperty(REF_END_PROPERTY, refEnd);
    }
    public Integer getRefEnd() {
        return (Integer)readProperty(REF_END_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

    public void setFeatureLoc(FeatureLocation featureLoc) {
        setToOneTarget(FEATURE_LOC_PROPERTY, featureLoc, true);
    }

    public FeatureLocation getFeatureLoc() {
        return (FeatureLocation)readProperty(FEATURE_LOC_PROPERTY);
    }


    public void addToMetatags(VariationMetatag obj) {
        addToManyTarget(METATAGS_PROPERTY, obj, true);
    }
    public void removeFromMetatags(VariationMetatag obj) {
        removeToManyTarget(METATAGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VariationMetatag> getMetatags() {
        return (List<VariationMetatag>)readProperty(METATAGS_PROPERTY);
    }


    public void addToVarAlmtNotes(VarAlmtNote obj) {
        addToManyTarget(VAR_ALMT_NOTES_PROPERTY, obj, true);
    }
    public void removeFromVarAlmtNotes(VarAlmtNote obj) {
        removeToManyTarget(VAR_ALMT_NOTES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VarAlmtNote> getVarAlmtNotes() {
        return (List<VarAlmtNote>)readProperty(VAR_ALMT_NOTES_PROPERTY);
    }


}
