package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.featureLoc.FeatureLocation;
import uk.ac.gla.cvr.gluetools.core.datamodel.positionVariation.PositionVariation;
import uk.ac.gla.cvr.gluetools.core.datamodel.varAlmtNote.VarAlmtNote;
import uk.ac.gla.cvr.gluetools.core.datamodel.vcatMembership.VcatMembership;

/**
 * Class _Variation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Variation extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String NAME_PROPERTY = "name";
    public static final String REF_END_PROPERTY = "refEnd";
    public static final String REF_START_PROPERTY = "refStart";
    public static final String REGEX_PROPERTY = "regex";
    public static final String TRANSLATION_TYPE_PROPERTY = "translationType";
    public static final String FEATURE_LOC_PROPERTY = "featureLoc";
    public static final String POSITION_VARIATIONS_PROPERTY = "positionVariations";
    public static final String VAR_ALMT_NOTES_PROPERTY = "varAlmtNotes";
    public static final String VCAT_MEMBERSHIPS_PROPERTY = "vcatMemberships";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String NAME_PK_COLUMN = "name";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setDisplayName(String displayName) {
        writeProperty(DISPLAY_NAME_PROPERTY, displayName);
    }
    public String getDisplayName() {
        return (String)readProperty(DISPLAY_NAME_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setRefEnd(Integer refEnd) {
        writeProperty(REF_END_PROPERTY, refEnd);
    }
    public Integer getRefEnd() {
        return (Integer)readProperty(REF_END_PROPERTY);
    }

    public void setRefStart(Integer refStart) {
        writeProperty(REF_START_PROPERTY, refStart);
    }
    public Integer getRefStart() {
        return (Integer)readProperty(REF_START_PROPERTY);
    }

    public void setRegex(String regex) {
        writeProperty(REGEX_PROPERTY, regex);
    }
    public String getRegex() {
        return (String)readProperty(REGEX_PROPERTY);
    }

    public void setTranslationType(String translationType) {
        writeProperty(TRANSLATION_TYPE_PROPERTY, translationType);
    }
    public String getTranslationType() {
        return (String)readProperty(TRANSLATION_TYPE_PROPERTY);
    }

    public void setFeatureLoc(FeatureLocation featureLoc) {
        setToOneTarget(FEATURE_LOC_PROPERTY, featureLoc, true);
    }

    public FeatureLocation getFeatureLoc() {
        return (FeatureLocation)readProperty(FEATURE_LOC_PROPERTY);
    }


    public void addToPositionVariations(PositionVariation obj) {
        addToManyTarget(POSITION_VARIATIONS_PROPERTY, obj, true);
    }
    public void removeFromPositionVariations(PositionVariation obj) {
        removeToManyTarget(POSITION_VARIATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PositionVariation> getPositionVariations() {
        return (List<PositionVariation>)readProperty(POSITION_VARIATIONS_PROPERTY);
    }


    public void addToVarAlmtNotes(VarAlmtNote obj) {
        addToManyTarget(VAR_ALMT_NOTES_PROPERTY, obj, true);
    }
    public void removeFromVarAlmtNotes(VarAlmtNote obj) {
        removeToManyTarget(VAR_ALMT_NOTES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VarAlmtNote> getVarAlmtNotes() {
        return (List<VarAlmtNote>)readProperty(VAR_ALMT_NOTES_PROPERTY);
    }


    public void addToVcatMemberships(VcatMembership obj) {
        addToManyTarget(VCAT_MEMBERSHIPS_PROPERTY, obj, true);
    }
    public void removeFromVcatMemberships(VcatMembership obj) {
        removeToManyTarget(VCAT_MEMBERSHIPS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VcatMembership> getVcatMemberships() {
        return (List<VcatMembership>)readProperty(VCAT_MEMBERSHIPS_PROPERTY);
    }


}
