package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.alignment.Alignment;
import uk.ac.gla.cvr.gluetools.core.datamodel.variation.Variation;

/**
 * Class _VarAlmtNote was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VarAlmtNote extends GlueDataObject {

    public static final String ALIGNMENT_PROPERTY = "alignment";
    public static final String VARIATION_PROPERTY = "variation";

    public static final String ALIGNMENT_NAME_PK_COLUMN = "ALIGNMENT_NAME";
    public static final String FEATURE_NAME_PK_COLUMN = "FEATURE_NAME";
    public static final String REFERENCE_NAME_PK_COLUMN = "REFERENCE_NAME";
    public static final String VARIATION_NAME_PK_COLUMN = "VARIATION_NAME";

    public void setAlignment(Alignment alignment) {
        setToOneTarget(ALIGNMENT_PROPERTY, alignment, true);
    }

    public Alignment getAlignment() {
        return (Alignment)readProperty(ALIGNMENT_PROPERTY);
    }


    public void setVariation(Variation variation) {
        setToOneTarget(VARIATION_PROPERTY, variation, true);
    }

    public Variation getVariation() {
        return (Variation)readProperty(VARIATION_PROPERTY);
    }


}
