package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.variation.Variation;

/**
 * Class _VariationMetatag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VariationMetatag extends GlueDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String VALUE_PROPERTY = "value";
    public static final String VARIATION_PROPERTY = "variation";

    public static final String FEATURE_NAME_PK_COLUMN = "feature_name";
    public static final String METATAG_NAME_PK_COLUMN = "metatag_name";
    public static final String REF_SEQ_NAME_PK_COLUMN = "ref_seq_name";
    public static final String VARIATION_NAME_PK_COLUMN = "variation_name";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setValue(String value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public String getValue() {
        return (String)readProperty(VALUE_PROPERTY);
    }

    public void setVariation(Variation variation) {
        setToOneTarget(VARIATION_PROPERTY, variation, true);
    }

    public Variation getVariation() {
        return (Variation)readProperty(VARIATION_PROPERTY);
    }


}
