package uk.ac.gla.cvr.gluetools.core.datamodel.auto;

import java.util.List;

import uk.ac.gla.cvr.gluetools.core.datamodel.GlueDataObject;
import uk.ac.gla.cvr.gluetools.core.datamodel.variationCategory.VariationCategory;
import uk.ac.gla.cvr.gluetools.core.datamodel.vcatMembership.VcatMembership;

/**
 * Class _VariationCategory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VariationCategory extends GlueDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String NOTIFIABILITY_PROPERTY = "notifiability";
    public static final String CHILDREN_PROPERTY = "children";
    public static final String MEMBERSHIPS_PROPERTY = "memberships";
    public static final String PARENT_PROPERTY = "parent";

    public static final String NAME_PK_COLUMN = "name";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setNotifiability(String notifiability) {
        writeProperty(NOTIFIABILITY_PROPERTY, notifiability);
    }
    public String getNotifiability() {
        return (String)readProperty(NOTIFIABILITY_PROPERTY);
    }

    public void addToChildren(VariationCategory obj) {
        addToManyTarget(CHILDREN_PROPERTY, obj, true);
    }
    public void removeFromChildren(VariationCategory obj) {
        removeToManyTarget(CHILDREN_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VariationCategory> getChildren() {
        return (List<VariationCategory>)readProperty(CHILDREN_PROPERTY);
    }


    public void addToMemberships(VcatMembership obj) {
        addToManyTarget(MEMBERSHIPS_PROPERTY, obj, true);
    }
    public void removeFromMemberships(VcatMembership obj) {
        removeToManyTarget(MEMBERSHIPS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<VcatMembership> getMemberships() {
        return (List<VcatMembership>)readProperty(MEMBERSHIPS_PROPERTY);
    }


    public void setParent(VariationCategory parent) {
        setToOneTarget(PARENT_PROPERTY, parent, true);
    }

    public VariationCategory getParent() {
        return (VariationCategory)readProperty(PARENT_PROPERTY);
    }


}
