package uk.ac.gla.cvr.gluetools.core.digs.importer.model.auto;

import java.util.Date;

import uk.ac.gla.cvr.gluetools.core.digs.importer.model.DigsObject;

/**
 * Class _Loci was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Loci extends DigsObject {

    public static final String ASSIGNED_NAME_PROPERTY = "assignedName";
    public static final String DATA_TYPE_PROPERTY = "dataType";
    public static final String EXTRACT_END_PROPERTY = "extractEnd";
    public static final String EXTRACT_START_PROPERTY = "extractStart";
    public static final String GENOME_STRUCTURE_PROPERTY = "genomeStructure";
    public static final String ORGANISM_PROPERTY = "organism";
    public static final String ORIENTATION_PROPERTY = "orientation";
    public static final String SCAFFOLD_PROPERTY = "scaffold";
    public static final String TARGET_NAME_PROPERTY = "targetName";
    public static final String TIMESTAMP_PROPERTY = "timestamp";
    public static final String VERSION_PROPERTY = "version";

    public static final String RECORD_ID_PK_COLUMN = "Record_ID";

    public void setAssignedName(String assignedName) {
        writeProperty(ASSIGNED_NAME_PROPERTY, assignedName);
    }
    public String getAssignedName() {
        return (String)readProperty(ASSIGNED_NAME_PROPERTY);
    }

    public void setDataType(String dataType) {
        writeProperty(DATA_TYPE_PROPERTY, dataType);
    }
    public String getDataType() {
        return (String)readProperty(DATA_TYPE_PROPERTY);
    }

    public void setExtractEnd(Integer extractEnd) {
        writeProperty(EXTRACT_END_PROPERTY, extractEnd);
    }
    public Integer getExtractEnd() {
        return (Integer)readProperty(EXTRACT_END_PROPERTY);
    }

    public void setExtractStart(Integer extractStart) {
        writeProperty(EXTRACT_START_PROPERTY, extractStart);
    }
    public Integer getExtractStart() {
        return (Integer)readProperty(EXTRACT_START_PROPERTY);
    }

    public void setGenomeStructure(String genomeStructure) {
        writeProperty(GENOME_STRUCTURE_PROPERTY, genomeStructure);
    }
    public String getGenomeStructure() {
        return (String)readProperty(GENOME_STRUCTURE_PROPERTY);
    }

    public void setOrganism(String organism) {
        writeProperty(ORGANISM_PROPERTY, organism);
    }
    public String getOrganism() {
        return (String)readProperty(ORGANISM_PROPERTY);
    }

    public void setOrientation(String orientation) {
        writeProperty(ORIENTATION_PROPERTY, orientation);
    }
    public String getOrientation() {
        return (String)readProperty(ORIENTATION_PROPERTY);
    }

    public void setScaffold(String scaffold) {
        writeProperty(SCAFFOLD_PROPERTY, scaffold);
    }
    public String getScaffold() {
        return (String)readProperty(SCAFFOLD_PROPERTY);
    }

    public void setTargetName(String targetName) {
        writeProperty(TARGET_NAME_PROPERTY, targetName);
    }
    public String getTargetName() {
        return (String)readProperty(TARGET_NAME_PROPERTY);
    }

    public void setTimestamp(Date timestamp) {
        writeProperty(TIMESTAMP_PROPERTY, timestamp);
    }
    public Date getTimestamp() {
        return (Date)readProperty(TIMESTAMP_PROPERTY);
    }

    public void setVersion(String version) {
        writeProperty(VERSION_PROPERTY, version);
    }
    public String getVersion() {
        return (String)readProperty(VERSION_PROPERTY);
    }

}
