package uk.ac.gla.cvr.gluetools.core.digs.importer.model.auto;

import java.util.Date;

import uk.ac.gla.cvr.gluetools.core.digs.importer.model.DigsObject;

/**
 * Class _LociLink was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LociLink extends DigsObject {

    public static final String EXTRACTED_ID_PROPERTY = "extractedId";
    public static final String LOCUS_ID_PROPERTY = "locusId";
    public static final String TIMESTAMP_PROPERTY = "timestamp";

    public static final String RECORD_ID_PK_COLUMN = "Record_ID";

    public void setExtractedId(Integer extractedId) {
        writeProperty(EXTRACTED_ID_PROPERTY, extractedId);
    }
    public Integer getExtractedId() {
        return (Integer)readProperty(EXTRACTED_ID_PROPERTY);
    }

    public void setLocusId(Integer locusId) {
        writeProperty(LOCUS_ID_PROPERTY, locusId);
    }
    public Integer getLocusId() {
        return (Integer)readProperty(LOCUS_ID_PROPERTY);
    }

    public void setTimestamp(Date timestamp) {
        writeProperty(TIMESTAMP_PROPERTY, timestamp);
    }
    public Date getTimestamp() {
        return (Date)readProperty(TIMESTAMP_PROPERTY);
    }

}
